version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.9
jobs:
  BuildAndDeployLawnnannySDK:
    docker:
      - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:  
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install openjdk-8-jdk
            sudo java -version
            echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
            sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
            sudo apt-get update
            sudo apt-get install sbt
            sudo apt install nodejs
            sudo nodejs --version
            sudo apt install npm
            sudo npm --version
      - run:
          name: Configure AWS Credentials
          command: |
            aws configure set aws_access_key_id $adminAccessKey
            aws configure set aws_secret_access_key $adminSecretAccessKey
            aws configure set default.region us-east-1
      - run:
          name: Get Access Token To Publish Package To Github
          command: |
            cd lawnnannysdk
            githubAccessToken=$(aws ssm get-parameters --names CircleCIAccessKey --query "Parameters[0].Value" --output text)
            npmrc=$(sed 's/PERSONAL-ACCESS-TOKEN/"$githubAccessToken"/' .npmrc)
            echo ${npmrc} > .npmrc
            cat .npmrc
      - run:
          name: Run Tests
          command: |
            cd lawnnannysdk
            sbt rootJVM/test
      - run:
          name: Generate ES Module
          command: |
            cd lawnnannysdk
            sbt fullOptJS
            mv ./root/js/target/scala-2.12/root-opt.js ./lawnnannysdk.js
      - run:
          name: Publish SDK
          command: |
            cd lawnnannysdk
            npm publish
workflows:
    version: 2
    buildAndDeploy:
        jobs:
            - BuildAndDeployLawnnannySDK